### PR TITLE
Pass the Express request object as context 

### PR DESCRIPTION
**Pull request by amazzeo**
Allows access to params and other portions of the request object.

### CODE REVIEW

**Comment by colthreepv** [comment]
mhm such a functionality change would definitely need some documentation.

What's the use case?
An API endpoint that checks some parts of the body only if some params is there?

Seems quite a niche from here

**Comment by amazzeo** [comment]
Sorry about the lack of detail. I'm implementing a [JSON API](http://jsonapi.org/) compliant API and there are some requirements in the specification that require members of the body to match the server's endpoint.

This is one in particular that applies to updating resources:

    A server MUST return 409 Conflict when processing a PATCH request in which the resource object's type and id do not match the server's endpoint.

This example from the spec shows the desired behavior with an endpoint like `/articles/:id`:
```
PATCH /articles/1 HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "To TDD or Not",
      "text": "TLDR; It's complicated... but check your test coverage regardless."
    }
  }
}
```

Here `type` and `id` must match the params in the server endpoint. By passing the entire request object this allows you to create validations that can verify this for you like:

```
{
 data: {
  id: Joi.number().valid(Joi.ref('$params.id'))
 }
}
```

References can still reach the body of the request by referencing the body in the in the request object: `Joi.ref('$body.my_value')`.

**Comment by colthreepv** [comment]
I appreciate this input.. I think it could end behind a flag. 
I was hoping to merge `0.5` before further develop, but Andrew is missing. 

If I can get npm permissions I will be back with some more activity

**Comment by amazzeo** [comment]
Sounds good. I'm happy to rework it as needed.

**Comment by AndrewKeig** [comment]
Sorry guys very busy week, will leave this with @colthreepv, please go ahead with o.5, many thanks.

**Comment by colthreepv** [comment]
Hi @amazzeo I brought your idea and commits in a new branch [`context-request`](/AndrewKeig/express-validation/tree/amazzeo/context-request)

I put this functionality behind the flag `contextRequest`, it can be turn on globally, or selectively for a specific route.

Please review the branch and drop some feedback.

Also on flag naming
Hardest task

**Comment by amazzeo** [comment]
Sorry for the delay in getting back to you! I think that works great, thanks for including it!

**Comment by jdelibas** [comment]
Is this functionality going to be put into the master branch? The code seems to be stagnating in @colthreepv 's branch.

**Comment by colthreepv** [comment]
Ouch.. quite some dust on this PR!
Sorry for absence, will work on this promptly :construction_worker:

**Comment by colthreepv** [comment]
merged and released 1.0.0

**Pull request closed without merging**
