### PR TITLE
Feature/resolve joi 11 breaking changes

### PR DESCRIPTION
**Pull request by 199911**
Joi return an array instead of string from version 11
This PR is to fix the breaking changes start from version 11
https://github.com/hapijs/joi/issues/1302

As it is a breaking changes, may need to have major version bump.

### CODE REVIEW

**Comment by knor-el-snor** [comment]
Only these changes make the tests fail? I implemented these in a fork of mine.

**Comment by rmharrison** [comment]
`npm:joi` has been deprecated 
Update to `npm:@hapi/joi@15`?

**Comment by 199911** [comment]
Looks like npm:@hapi/joi@15 does not support nodejs 4.0
Trying other version of joi

**Comment by 199911** [comment]
@rmharrison 
joi@13 only support Node.js 8 or above
https://github.com/hapijs/joi/issues/1327

We can either use joi@12 or drop the support on Node.js below version 8

**Pull request closed without merging**
