### PR TITLE
Cookies validation

### PR DESCRIPTION
**Pull request by aymericbeaumet**
- Enable cookies validation
- Add the `/logout` test endpoint which requires cookies to be set

Closes https://github.com/AndrewKeig/express-validation/issues/12

### CODE REVIEW

**Comment by aymericbeaumet** [comment]
rfr @mrgamer @AndrewKeig

**Comment by mrgamer** [comment]
LGTM, Thanks Aymeric

**Comment by mrgamer** [comment]
feature is up, needs @AndrewKeig `npm publish` when he can ;) have a nice weekend

**Comment by AndrewKeig** [comment]
Hey all, thanks for sorting this out, its now up on npm, cheers..

**Comment by aymericbeaumet** [comment]
Awesome, thanks guys!

**Pull request merged**
