### PR TITLE
fix: Update joi-dependency

### LINKED ISSUE #92: Error in package Joi
The package joi was changed to @hapi/joi.

Erro: Cannot find module 'joi'.

It was necessary to change from joi to @hapi/joi at lib/index.js

### PR DESCRIPTION
**Pull request by juliuscc**
`joi` is depricated and moved to `@hapi/joi`. Users of express-validation can not upgrade their `joi` to new versions as that fork is stuck in version 14.3.1. This would allow users of the library to use the new versions of `joi`.

Fixes #92.

### CODE REVIEW

**Comment by juliuscc** [comment]
I was not sure if I should add anything to the changelog.

Another concern I have is if users want to update to `hapi/joi`. If not then they would be forced to. This is a major change I think. There might be a way to accept either `hapi/joi` being installed *or* `joi`. I do not know how that would work though.

It is however important to do this change at one point as I am personally blocked from using new joi features.

**Comment by isaachinman** [comment]
1. You've referenced `@hapi/joi` without even installing it
2. Normally for something like this, we'd need to bump the major and update the peer dep in `package.json`

**Comment by juliuscc** [comment]
I am sorry! I missed some files, and I also missed that there are 2 PRs before mine. Now I updated this so it is basically #94 but with a fixed package.json. I also did not commit changes to the code in lib/index.js

**Comment by Gameghostify** [comment]
> I was not sure if I should add anything to the changelog.
> 
> Another concern I have is if users want to update to `hapi/joi`. If not then they would be forced to. This is a major change I think. There might be a way to accept either `hapi/joi` being installed _or_ `joi`. I do not know how that would work though.
> 
> It is however important to do this change at one point as I am personally blocked from using new joi features.

A possible fix would be to default to "@hapi/joi", but let the user pass in their own `Joi` instance, wouldn't it?

This also would be a great feature since then everyone could make use of their own instances instead of needing to use the default one

**Comment by isaachinman** [comment]
> but let the user pass in their own Joi instance

No, that doesn't seem like a great idea. We'd update the dep and release a new major.

**Comment by juliuscc** [comment]
What would the next step be before this is merged? Is there anything missing from the PR?

**Comment by jschatz1** [comment]
Any plans to merge this, or should I find alternatives? This seems close.

**Comment by juliuscc** [comment]
We switched to celebrate. It offers the same functionality but is maintained

**Comment by AndrewKeig** [comment]
Closing this, version 2.0.0 of this module, now supports joi 15.

**Pull request closed without merging**
