### PR TITLE
Added declaration files

### LINKED ISSUE #54: TypeScript definitions
Hi,

Any plans to add typescript definitions?

Thanks.

### PR DESCRIPTION
**Pull request by fega**
Fixes #54.

still not tested

### CODE REVIEW

**Comment by fega** [comment]
@AndrewKeig Hello Andrew, I just added those typings and are working fine.

would be nice if you check it and merge it :)

**Comment by isaachinman** [comment]
@fega To your knowledge, is this still up-to-date? If so we can get it merged. Thanks.

**Comment by fega** [comment]
Hello @isaachinman thanks for your response, I think it can be improved,  I'll try to check in this week to see what can be improved :)

**Comment by isaachinman** [comment]
@fega Thanks. Let me know when you have an update. First-class TypeScript support is something we'll prioritise going forward.

**Comment by colthreepv** [comment]
Why not make a PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) ?

They also have a way to test the types

**Comment by isaachinman** [comment]
@colthreepv That'd be fine too, but I personally prefer to maintain types within the repo itself.

**Comment by nivnahmias** [comment]
please merge this

**Comment by isaachinman** [comment]
@nivnahmias Does this fix #54?

**Comment by nivnahmias** [comment]
Yes

**Pull request merged**
