### PR TITLE
Extend request variable in validate() to add support for defaults

### PR DESCRIPTION
**Pull request by iheanyi**
The way things are now, you are losing Joi.default() values because of your middleware. With this change, the final value is extended with the values from defaults and will be available in the body, query params, or wherever. Let me know if you want me to add more extensive tests.

### CODE REVIEW

**Comment by iheanyi** [comment]
Let me know if you want me to add more tests and I'll gladly do so.

**Comment by mrgamer** [comment]
I like this PR ;) a word from the author might be nice, but I think he approves this functionality as it reflects Joi.
Maybe would be nice a couple of lines of documentation, just saying that Joi.default() works.
I will wait a couple days and then merge with or w/o markdown

thanks for your contribution!

**Comment by iheanyi** [comment]
@mrgamer – Do you think that it even needs to be added to the documentation, in reality? Considering that it's expected behavior. I was actually stumped when I was trying to use Joi's default feature and it wasn't working, so I dunno how much benefit documentation actually adds. And you're welcome, just happy to contribute!

**Comment by AndrewKeig** [comment]
@iheanyi, thanks for this, and yes I think you are right, if its Joi default behaviour we should support this.
No need to update the docs.

**Comment by iheanyi** [comment]
:+1:

**Comment by AndrewKeig** [comment]
This is up on npm, thanks again.

**Pull request merged**
