### PR TITLE
Allow unknown fields

### PR DESCRIPTION
**Pull request by YonatanKiron**

### CODE REVIEW

**Review by asafel — APPROVED** [review]

**Comment by YonatanKiron** [comment]
@AndrewKeig Any update?

**Comment by papandreou** [comment]
Can you elaborate a bit on the use case for this? And maybe include a unit test or two?

**Comment by papandreou** [comment]
This test proves that it's fine to have other middleware that adds properties to the `request` object: https://github.com/AndrewKeig/express-validation/commit/5b8b4015c62c20ef006182a2e5a40df10181e294

... but I'm probably misunderstanding exactly what it is that you're trying to do.

**Comment by papandreou** [comment]
Closing due to inactivity.

**Pull request closed without merging**
