### PR TITLE
Added 'mutateRequest' option.

### PR DESCRIPTION
**Pull request by vzhidal**
Hey @AndrewKeig 

Can we add this flag in your library options?

### CODE REVIEW

**Comment by colthreepv** [comment]
Hi, thanks for the contribution, what's the use case for this?

There is an opposite PR #46 that I am actually inclined to merge, but haven't thought about the repercussions enough.

**Comment by vzhidal** [comment]
As for me validation and types conversion are 2 different issues. In most cases that is great to have one config and processor for both of them, but sometimes type conversion is not acceptable through this config. So I think that would be great to have an option for disabling a request mutation.

**Comment by colthreepv** [comment]
I tend to agree with #46 and #45 - I would rather *not* mutate request in this library, either not mutate at all, or if `mutateRequest` is enabled, just replace request[something] from Joi output.

So I think we can find a way to make every user happy, except.. documentation is important for every new option

**Comment by awilkins** [comment]
AFAICT this will suppress mutations of existing keys when disabled but when enabled not cover cases where keys are removed (inc. renames) because it still calls `_assignIn()`

**Comment by colthreepv** [comment]
from what I understood @vzhidal wants to opt-out of mutating request keys in certain cases

when "enabled" I plan to just use the agreed functionality in #46 (thus mutating request keys with Joi outputs)

**Comment by colthreepv** [comment]
Merged, remember me to put you on contributors

**Pull request closed without merging**
