### PR TITLE
adds support for stripping unknown parameters in the request body

### PR DESCRIPTION
**Pull request by wilwizard**

### CODE REVIEW

**Comment by AshtonRoute** [comment]
why not simply use lodash since it's already there:
```javascript
var joiOptions = assignIn(schema._settings, {
    context: context || request,
    allowUnknown: allowUnknown,
    abortEarly: false
  });
```

it will respect user's settings keeping defaults.

**Comment by colthreepv** [comment]
post-poning this PR after #46 gets in

**Comment by sseetal** [comment]
Hi...is there a update on when this will be merged. Would love to have this feature! Thanks!

**Comment by fega** [comment]
@AndrewKeig I'm also awaiting this feature

**Comment by isaachinman** [comment]
This is breaking, is it not? If we're going to break the function signature, we may as well think about converting to a single argument object. That will make it easier to modify params in the future without breaking changes.

**Comment by AndrewKeig** [comment]
Closing, released 3.0

**Pull request closed without merging**
